### ISSUE TITLE
створюэмо таблицю player_process_banned

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#10]
і реалізовуемо процес закриття кліента при при перевірці кожної хвилини і знаходженні забороненого процеса

**Comment by insqq** [comment]
ти наповниш цю таблицю забороненими процесами і якшо лаунчер в гравця найде якийсь процес з цієї таблиці то закривати клієнт та лаунчер і банити гравця?

**Comment by lyovav** [comment]
саме так

**Comment by insqq** [comment]
требуде протестити нормально. або БД зараз вимкнена
