### ISSUE TITLE
інший метод отримання ІД проца

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#11]
MOS = new ManagementObjectSearcher("Select * From Win32_processor");
foreach (ManagementObject getPID in MOS.Get())
{
textBox2.Text = getPID["ProcessorID"].ToString();
}

**Comment by lyovav** [comment]
using System.management;


//Code for retrieving motherboard's serial number
ManagementObjectSearcher MOS = new ManagementObjectSearcher("Select * From Win32_BaseBoard");
foreach (ManagementObject getserial in MOS.Get())
{
textBox1.Text = getserial["SerialNumber"].ToString();
}

**Comment by insqq** [comment]
в мене  на віртуал боксі він повертає 0, тестану ше дома.
