### ISSUE TITLE
вивести окремо адресу cайта та версію лаунчера

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#13]
const string website = "dayz.lyova.name";
const string version = "1.0.0";

**Comment by lyovav** [comment]
добаыляемо
const string MessageBoxTitle = "dayz by lyova";

та пререписуемо код  в MessageBox.Show
MessageBox.Show("Error: You are banned!", (MessageBoxTitle),

**Comment by lyovav** [comment]
private void btnWebSite_Click(object sender, EventArgs e)
 адресу берем з const string website = "dayz.lyova.name"; 
      {
            try
            {
                Process.Start("http://dz.lyova.name");
            }
            catch (Exception) { }

**Comment by lyovav** [comment]
версію лаунчера вивести десь у выкны лаунчера

**Comment by insqq** [comment]
![default](https://cloud.githubusercontent.com/assets/10553744/9035158/0609a920-39de-11e5-8be4-0a1c5f394a39.PNG)

подивись чи в тебе в апконфігу незахардкожений твій нік при компіляції.
