### ISSUE TITLE
список запущених програм нап компі гравція - формуемо та заносимо в базу данних в поле грваця

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#2]
можна таке реалізувати як лаунчером подивитися список запущених програм нап компі гравція?

**Comment by lyovav** [comment]
поле в таблиці PPclient

**Comment by lyovav** [comment]
для забанених процесів поле поле в таблиці PPclientBanned

**Comment by lyovav** [comment]
по можлмвості добавити колонку опис процессу

**Comment by insqq** [comment]
https://msdn.microsoft.com/ru-ru/library/system.diagnostics.process%28v=vs.110%29.aspx
тут є таблиця свойств процесу, які свойства добавити в опис?

**Comment by lyovav** [comment]
MainWindowTitle
