### ISSUE TITLE
змінилися параметри запуска гри

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#3]
наприклад це все одна строка

dta\client.bin (запуск з папки) 

-cpuCount=4 -maxMem=16384 -maxVram=4096 -exThreads=3 (берем з лаунчара) 

-high -noSplash -noPause -cfg=user_cfg\basic.cfg -profiles=user_cfg -noLogs (обовязкові параметри) 

-name=(берем з лаунчера)

-password= (у шифрованому вигряди)

**Comment by lyovav** [comment]
з батніка гра запускається
start dta\client.bin -cpuCount=4 -maxMem=16384 -maxVram=4096 -exThreads=3 -high -noSplash -noPause -cfg=user_cfg\basic.cfg -profiles=user_cfg -noLogs -name=lion
з лаунчера ні(

**Comment by insqq** [comment]
ти в батніку невказуєш ІП та порт та мод ?
де саме ти його вказуєш ?

**Comment by lyovav** [comment]
я мав на увазі що лаунчер взвгалі не запускаэ кліент
        const string serverip = "94.231.177.50\n";
        const string serverport = "2302\n";

**Comment by insqq** [comment]
вроді поправив. треба перевіряти

**Comment by insqq** [comment]
попробуєш ще разом з лаунчером копірувати ддлк mysql.data.dll лаунчер вроді залежний від неї

**Comment by lyovav** [comment]
запускаючий файл е в папці dta/client.bin
не екзешка
зараз лаунчер не знає чим той файл відкрити або як
