### ISSUE TITLE
чистимо лог файли у папці з ігрою при старті лаунчера

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#8]
del *.log
del user_cfg\*.rpt

**Comment by insqq** [comment]
видалити всі файли в корені гри з розширеням .log? і всі файли в папці user_cfg з розширеням .rpt? я вірно зрузмів?

**Comment by lyovav** [comment]
так rpt

**Comment by insqq** [comment]
логи чистити все ще треба? ато я бачу ти закривав задачу?

**Comment by lyovav** [comment]
сорі не т онатиснув все ще тре

**Comment by lyovav** [comment]
вискакуэ вікно з кенопкою ОК для підтвердження видалення кожного файла в папці

**Comment by insqq** [comment]
поправив

**Comment by lyovav** [comment]
добавляем перевірку на обем файла ,  файли .log якщо вони быльше 20 килобайт

**Comment by insqq** [comment]
готово
