### ISSUE TITLE
добавляемо параметр в запуск -password=

### ISSUE THREAD

**Issue by lyovav** [insqq/Launcher#9]
-password=serverpass

serverpass пишеться у відкритому вигляді і при відкритті файла можно його прочитати
треба якось його зашифрувати

**Comment by insqq** [comment]
де він пишиться і звідки считується і чим?. качаю клієнт шоб ліпше в тому всьому розібратись і тестанути запуск

**Comment by lyovav** [comment]
буде використовуватись в аргуметнтах
string Arguments = "-name=" + tbNickName.Text + "\n" + " -connect=" + serverip + " -port=" + serverport + servermod + "" + startgame + "";

const string serverpassswod = "serverpass в кодованому вигляді\n";

тобто якщо я напишу у відкритому вигляді його 
-password=serverpass то його при декомпіляціі вичислять

**Comment by insqq** [comment]
ти хочеш передавати скритий аргумент на сервер шоб потім на сервері ідентифікувати чи запуск клієнта відбувся з лаунчера?

**Comment by lyovav** [comment]
ні я задаю цей параметр в лаунчері і тільки в ньому але якщо я лишу його відкритим текстом то його вичислять зразу тре якось йогов лаунчері замаскувати

**Comment by lyovav** [comment]
я ісходами сервера ще не розжився тому передавати на сервер незможу

**Comment by insqq** [comment]
попробую потім шось таке зробити 
https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%84%D1%83%D1%81%D0%BA%D0%B0%D1%86%D0%B8%D1%8F
але ше ніразу таким некористувався

**Comment by insqq** [comment]
параметр я добавлю. скинеш мені який саме пароль. а закодувати його попробуєш тою програмою. подивись відео то шо я кинув там розказується і показується шо і як працює

**Comment by insqq** [comment]
скинеш в скайп звідки качав обфускатор потещу його ше в себе. і пароль який поставити.
